// Generated by rstantools.  Do not edit by hand.

/*
    BuLTM is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BuLTM is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BuLTM.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1
#include <stan/model/model_header.hpp>
namespace model_trans_unknow_shrinkage_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'trans_unknow_shrinkage', line 20, column 3 to column 18)",
                                                      " (in 'trans_unknow_shrinkage', line 23, column 2 to column 24)",
                                                      " (in 'trans_unknow_shrinkage', line 24, column 2 to column 27)",
                                                      " (in 'trans_unknow_shrinkage', line 25, column 2 to column 32)",
                                                      " (in 'trans_unknow_shrinkage', line 26, column 2 to column 32)",
                                                      " (in 'trans_unknow_shrinkage', line 27, column 2 to column 39)",
                                                      " (in 'trans_unknow_shrinkage', line 31, column 2 to column 24)",
                                                      " (in 'trans_unknow_shrinkage', line 32, column 2 to column 23)",
                                                      " (in 'trans_unknow_shrinkage', line 33, column 24 to column 70)",
                                                      " (in 'trans_unknow_shrinkage', line 33, column 22 to column 71)",
                                                      " (in 'trans_unknow_shrinkage', line 33, column 2 to column 71)",
                                                      " (in 'trans_unknow_shrinkage', line 34, column 2 to column 46)",
                                                      " (in 'trans_unknow_shrinkage', line 67, column 2 to column 28)",
                                                      " (in 'trans_unknow_shrinkage', line 68, column 2 to column 20)",
                                                      " (in 'trans_unknow_shrinkage', line 69, column 2 to column 47)",
                                                      " (in 'trans_unknow_shrinkage', line 71, column 4 to column 15)",
                                                      " (in 'trans_unknow_shrinkage', line 72, column 4 to column 16)",
                                                      " (in 'trans_unknow_shrinkage', line 73, column 11 to column 12)",
                                                      " (in 'trans_unknow_shrinkage', line 73, column 4 to column 20)",
                                                      " (in 'trans_unknow_shrinkage', line 74, column 4 to column 56)",
                                                      " (in 'trans_unknow_shrinkage', line 75, column 4 to column 57)",
                                                      " (in 'trans_unknow_shrinkage', line 82, column 7 to column 99)",
                                                      " (in 'trans_unknow_shrinkage', line 82, column 6 to column 100)",
                                                      " (in 'trans_unknow_shrinkage', line 79, column 7 to line 80, column 26)",
                                                      " (in 'trans_unknow_shrinkage', line 79, column 6 to line 80, column 27)",
                                                      " (in 'trans_unknow_shrinkage', line 78, column 6 to line 82, column 100)",
                                                      " (in 'trans_unknow_shrinkage', line 77, column 17 to line 83, column 5)",
                                                      " (in 'trans_unknow_shrinkage', line 77, column 4 to line 83, column 5)",
                                                      " (in 'trans_unknow_shrinkage', line 84, column 2 to column 35)",
                                                      " (in 'trans_unknow_shrinkage', line 70, column 16 to line 85, column 1)",
                                                      " (in 'trans_unknow_shrinkage', line 70, column 0 to line 85, column 1)",
                                                      " (in 'trans_unknow_shrinkage', line 38, column 2 to column 25)",
                                                      " (in 'trans_unknow_shrinkage', line 39, column 2 to column 22)",
                                                      " (in 'trans_unknow_shrinkage', line 40, column 2 to column 19)",
                                                      " (in 'trans_unknow_shrinkage', line 41, column 2 to column 22)",
                                                      " (in 'trans_unknow_shrinkage', line 44, column 2 to column 21)",
                                                      " (in 'trans_unknow_shrinkage', line 45, column 2 to column 24)",
                                                      " (in 'trans_unknow_shrinkage', line 49, column 4 to column 15)",
                                                      " (in 'trans_unknow_shrinkage', line 50, column 4 to column 16)",
                                                      " (in 'trans_unknow_shrinkage', line 51, column 11 to column 12)",
                                                      " (in 'trans_unknow_shrinkage', line 51, column 4 to column 20)",
                                                      " (in 'trans_unknow_shrinkage', line 52, column 4 to column 55)",
                                                      " (in 'trans_unknow_shrinkage', line 53, column 4 to column 56)",
                                                      " (in 'trans_unknow_shrinkage', line 60, column 7 to column 98)",
                                                      " (in 'trans_unknow_shrinkage', line 60, column 6 to column 99)",
                                                      " (in 'trans_unknow_shrinkage', line 57, column 7 to line 58, column 25)",
                                                      " (in 'trans_unknow_shrinkage', line 57, column 6 to line 58, column 26)",
                                                      " (in 'trans_unknow_shrinkage', line 56, column 6 to line 60, column 99)",
                                                      " (in 'trans_unknow_shrinkage', line 55, column 17 to line 61, column 5)",
                                                      " (in 'trans_unknow_shrinkage', line 55, column 4 to line 61, column 5)",
                                                      " (in 'trans_unknow_shrinkage', line 63, column 4 to column 33)",
                                                      " (in 'trans_unknow_shrinkage', line 48, column 17 to line 64, column 3)",
                                                      " (in 'trans_unknow_shrinkage', line 48, column 2 to line 64, column 3)",
                                                      " (in 'trans_unknow_shrinkage', line 2, column 2 to column 17)",
                                                      " (in 'trans_unknow_shrinkage', line 3, column 2 to column 25)",
                                                      " (in 'trans_unknow_shrinkage', line 4, column 2 to column 17)",
                                                      " (in 'trans_unknow_shrinkage', line 5, column 2 to column 22)",
                                                      " (in 'trans_unknow_shrinkage', line 7, column 2 to column 17)",
                                                      " (in 'trans_unknow_shrinkage', line 8, column 2 to column 18)",
                                                      " (in 'trans_unknow_shrinkage', line 9, column 9 to column 18)",
                                                      " (in 'trans_unknow_shrinkage', line 9, column 20 to column 22)",
                                                      " (in 'trans_unknow_shrinkage', line 9, column 2 to column 32)",
                                                      " (in 'trans_unknow_shrinkage', line 10, column 9 to column 18)",
                                                      " (in 'trans_unknow_shrinkage', line 10, column 20 to column 22)",
                                                      " (in 'trans_unknow_shrinkage', line 10, column 2 to column 32)",
                                                      " (in 'trans_unknow_shrinkage', line 11, column 9 to column 10)",
                                                      " (in 'trans_unknow_shrinkage', line 11, column 2 to column 14)",
                                                      " (in 'trans_unknow_shrinkage', line 12, column 15 to column 16)",
                                                      " (in 'trans_unknow_shrinkage', line 12, column 2 to column 18)",
                                                      " (in 'trans_unknow_shrinkage', line 13, column 9 to column 10)",
                                                      " (in 'trans_unknow_shrinkage', line 13, column 2 to column 18)",
                                                      " (in 'trans_unknow_shrinkage', line 14, column 9 to column 10)",
                                                      " (in 'trans_unknow_shrinkage', line 14, column 11 to column 12)",
                                                      " (in 'trans_unknow_shrinkage', line 14, column 2 to column 16)",
                                                      " (in 'trans_unknow_shrinkage', line 16, column 9 to column 10)",
                                                      " (in 'trans_unknow_shrinkage', line 16, column 2 to column 23)",
                                                      " (in 'trans_unknow_shrinkage', line 17, column 27 to column 28)",
                                                      " (in 'trans_unknow_shrinkage', line 17, column 2 to column 38)",
                                                      " (in 'trans_unknow_shrinkage', line 20, column 10 to column 11)",
                                                      " (in 'trans_unknow_shrinkage', line 23, column 18 to column 19)",
                                                      " (in 'trans_unknow_shrinkage', line 24, column 18 to column 19)",
                                                      " (in 'trans_unknow_shrinkage', line 25, column 27 to column 28)",
                                                      " (in 'trans_unknow_shrinkage', line 26, column 18 to column 27)",
                                                      " (in 'trans_unknow_shrinkage', line 27, column 22 to column 31)",
                                                      " (in 'trans_unknow_shrinkage', line 31, column 10 to column 11)",
                                                      " (in 'trans_unknow_shrinkage', line 67, column 14 to column 15)",
                                                      " (in 'trans_unknow_shrinkage', line 68, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_trans_unknow_shrinkage final : public model_base_crtp<model_trans_unknow_shrinkage> {
 private:
  int p;
  int num_basis;
  int K;
  double alpha;
  int n;
  int NN;
  Eigen::Matrix<double, -1, -1> Yspline;
  Eigen::Matrix<double, -1, -1> yspline;
  Eigen::Matrix<double, -1, 1> Y;
  std::vector<int> location;
  Eigen::Matrix<double, -1, 1> delta;
  Eigen::Matrix<double, -1, -1> X;
  Eigen::Matrix<double, -1, 1> beta_init0;
  Eigen::Matrix<double, -1, 1> w_init0;
 
 public:
  ~model_trans_unknow_shrinkage() { }
  
  inline std::string model_name() const final { return "model_trans_unknow_shrinkage"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1", "stancflags = "};
  }
  
  
  model_trans_unknow_shrinkage(stan::io::var_context& context__,
                               unsigned int random_seed__ = 0,
                               std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_trans_unknow_shrinkage_namespace::model_trans_unknow_shrinkage";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 54;
      context__.validate_dims("data initialization","p","int",
          context__.to_vec());
      p = std::numeric_limits<int>::min();
      
      current_statement__ = 54;
      p = context__.vals_i("p")[(1 - 1)];
      current_statement__ = 54;
      current_statement__ = 54;
      check_greater_or_equal(function__, "p", p, 1);
      current_statement__ = 55;
      context__.validate_dims("data initialization","num_basis","int",
          context__.to_vec());
      num_basis = std::numeric_limits<int>::min();
      
      current_statement__ = 55;
      num_basis = context__.vals_i("num_basis")[(1 - 1)];
      current_statement__ = 55;
      current_statement__ = 55;
      check_greater_or_equal(function__, "num_basis", num_basis, 1);
      current_statement__ = 56;
      context__.validate_dims("data initialization","K","int",
          context__.to_vec());
      K = std::numeric_limits<int>::min();
      
      current_statement__ = 56;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 56;
      current_statement__ = 56;
      check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 57;
      context__.validate_dims("data initialization","alpha","double",
          context__.to_vec());
      alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 57;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      current_statement__ = 57;
      current_statement__ = 57;
      check_greater_or_equal(function__, "alpha", alpha, 0);
      current_statement__ = 58;
      context__.validate_dims("data initialization","n","int",
          context__.to_vec());
      n = std::numeric_limits<int>::min();
      
      current_statement__ = 58;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 58;
      current_statement__ = 58;
      check_greater_or_equal(function__, "n", n, 1);
      current_statement__ = 59;
      context__.validate_dims("data initialization","NN","int",
          context__.to_vec());
      NN = std::numeric_limits<int>::min();
      
      current_statement__ = 59;
      NN = context__.vals_i("NN")[(1 - 1)];
      current_statement__ = 59;
      current_statement__ = 59;
      check_greater_or_equal(function__, "NN", NN, 1);
      current_statement__ = 60;
      validate_non_negative_index("Yspline", "num_basis", num_basis);
      current_statement__ = 61;
      validate_non_negative_index("Yspline", "NN", NN);
      current_statement__ = 62;
      context__.validate_dims("data initialization","Yspline","double",
          context__.to_vec(num_basis, NN));
      Yspline = Eigen::Matrix<double, -1, -1>(num_basis, NN);
      stan::math::fill(Yspline, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> Yspline_flat__;
        current_statement__ = 62;
        assign(Yspline_flat__, nil_index_list(), context__.vals_r("Yspline"),
          "assigning variable Yspline_flat__");
        current_statement__ = 62;
        pos__ = 1;
        current_statement__ = 62;
        for (int sym1__ = 1; sym1__ <= NN; ++sym1__) {
          current_statement__ = 62;
          for (int sym2__ = 1; sym2__ <= num_basis; ++sym2__) {
            current_statement__ = 62;
            assign(Yspline,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              Yspline_flat__[(pos__ - 1)], "assigning variable Yspline");
            current_statement__ = 62;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 63;
      validate_non_negative_index("yspline", "num_basis", num_basis);
      current_statement__ = 64;
      validate_non_negative_index("yspline", "NN", NN);
      current_statement__ = 65;
      context__.validate_dims("data initialization","yspline","double",
          context__.to_vec(num_basis, NN));
      yspline = Eigen::Matrix<double, -1, -1>(num_basis, NN);
      stan::math::fill(yspline, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> yspline_flat__;
        current_statement__ = 65;
        assign(yspline_flat__, nil_index_list(), context__.vals_r("yspline"),
          "assigning variable yspline_flat__");
        current_statement__ = 65;
        pos__ = 1;
        current_statement__ = 65;
        for (int sym1__ = 1; sym1__ <= NN; ++sym1__) {
          current_statement__ = 65;
          for (int sym2__ = 1; sym2__ <= num_basis; ++sym2__) {
            current_statement__ = 65;
            assign(yspline,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              yspline_flat__[(pos__ - 1)], "assigning variable yspline");
            current_statement__ = 65;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 66;
      validate_non_negative_index("Y", "n", n);
      current_statement__ = 67;
      context__.validate_dims("data initialization","Y","double",
          context__.to_vec(n));
      Y = Eigen::Matrix<double, -1, 1>(n);
      stan::math::fill(Y, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> Y_flat__;
        current_statement__ = 67;
        assign(Y_flat__, nil_index_list(), context__.vals_r("Y"),
          "assigning variable Y_flat__");
        current_statement__ = 67;
        pos__ = 1;
        current_statement__ = 67;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 67;
          assign(Y, cons_list(index_uni(sym1__), nil_index_list()),
            Y_flat__[(pos__ - 1)], "assigning variable Y");
          current_statement__ = 67;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 68;
      validate_non_negative_index("location", "n", n);
      current_statement__ = 69;
      context__.validate_dims("data initialization","location","int",
          context__.to_vec(n));
      location = std::vector<int>(n, std::numeric_limits<int>::min());
      
      current_statement__ = 69;
      assign(location, nil_index_list(), context__.vals_i("location"),
        "assigning variable location");
      current_statement__ = 70;
      validate_non_negative_index("delta", "n", n);
      current_statement__ = 71;
      context__.validate_dims("data initialization","delta","double",
          context__.to_vec(n));
      delta = Eigen::Matrix<double, -1, 1>(n);
      stan::math::fill(delta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> delta_flat__;
        current_statement__ = 71;
        assign(delta_flat__, nil_index_list(), context__.vals_r("delta"),
          "assigning variable delta_flat__");
        current_statement__ = 71;
        pos__ = 1;
        current_statement__ = 71;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 71;
          assign(delta, cons_list(index_uni(sym1__), nil_index_list()),
            delta_flat__[(pos__ - 1)], "assigning variable delta");
          current_statement__ = 71;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 72;
      validate_non_negative_index("X", "n", n);
      current_statement__ = 73;
      validate_non_negative_index("X", "p", p);
      current_statement__ = 74;
      context__.validate_dims("data initialization","X","double",
          context__.to_vec(n, p));
      X = Eigen::Matrix<double, -1, -1>(n, p);
      stan::math::fill(X, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 74;
        assign(X_flat__, nil_index_list(), context__.vals_r("X"),
          "assigning variable X_flat__");
        current_statement__ = 74;
        pos__ = 1;
        current_statement__ = 74;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          current_statement__ = 74;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 74;
            assign(X,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              X_flat__[(pos__ - 1)], "assigning variable X");
            current_statement__ = 74;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 75;
      validate_non_negative_index("beta_init0", "p", p);
      current_statement__ = 76;
      context__.validate_dims("data initialization","beta_init0","double",
          context__.to_vec(p));
      beta_init0 = Eigen::Matrix<double, -1, 1>(p);
      stan::math::fill(beta_init0, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> beta_init0_flat__;
        current_statement__ = 76;
        assign(beta_init0_flat__, nil_index_list(),
          context__.vals_r("beta_init0"),
          "assigning variable beta_init0_flat__");
        current_statement__ = 76;
        pos__ = 1;
        current_statement__ = 76;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          current_statement__ = 76;
          assign(beta_init0, cons_list(index_uni(sym1__), nil_index_list()),
            beta_init0_flat__[(pos__ - 1)], "assigning variable beta_init0");
          current_statement__ = 76;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 77;
      validate_non_negative_index("w_init0", "K", K);
      current_statement__ = 78;
      context__.validate_dims("data initialization","w_init0","double",
          context__.to_vec(K));
      w_init0 = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(w_init0, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> w_init0_flat__;
        current_statement__ = 78;
        assign(w_init0_flat__, nil_index_list(), context__.vals_r("w_init0"),
          "assigning variable w_init0_flat__");
        current_statement__ = 78;
        pos__ = 1;
        current_statement__ = 78;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 78;
          assign(w_init0, cons_list(index_uni(sym1__), nil_index_list()),
            w_init0_flat__[(pos__ - 1)], "assigning variable w_init0");
          current_statement__ = 78;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 78;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 78;
        current_statement__ = 78;
        check_greater_or_equal(function__, "w_init0[sym1__]",
                               w_init0[(sym1__ - 1)], 0);}
      current_statement__ = 78;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 78;
        current_statement__ = 78;
        check_less_or_equal(function__, "w_init0[sym1__]",
                            w_init0[(sym1__ - 1)], 1);}
      current_statement__ = 79;
      validate_non_negative_index("beta", "p", p);
      current_statement__ = 80;
      validate_non_negative_index("nu", "K", K);
      current_statement__ = 81;
      validate_non_negative_index("theta", "K", K);
      current_statement__ = 82;
      validate_non_negative_index("w", "K", K);
      current_statement__ = 83;
      validate_non_negative_index("mu", "num_basis", num_basis);
      current_statement__ = 84;
      validate_non_negative_index("a_raw", "num_basis", num_basis);
      current_statement__ = 85;
      validate_non_negative_index("DP_weights", "K", K);
      current_statement__ = 86;
      validate_non_negative_index("beta_trans", "p", p);
      current_statement__ = 87;
      validate_non_negative_index("log_lik", "n", n);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += p;
      num_params_r__ += K;
      num_params_r__ += K;
      num_params_r__ += K;
      num_params_r__ += num_basis;
      num_params_r__ += num_basis;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_trans_unknow_shrinkage_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> beta;
      beta = Eigen::Matrix<local_scalar_t__, -1, 1>(p);
      stan::math::fill(beta, DUMMY_VAR__);
      
      current_statement__ = 1;
      beta = in__.vector(p);
      Eigen::Matrix<local_scalar_t__, -1, 1> nu;
      nu = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(nu, DUMMY_VAR__);
      
      current_statement__ = 2;
      nu = in__.vector(K);
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 2;
        if (jacobian__) {
          current_statement__ = 2;
          assign(nu, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(nu[(sym1__ - 1)], 0, lp__),
            "assigning variable nu");
        } else {
          current_statement__ = 2;
          assign(nu, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(nu[(sym1__ - 1)], 0),
            "assigning variable nu");
        }}
      Eigen::Matrix<local_scalar_t__, -1, 1> theta;
      theta = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(theta, DUMMY_VAR__);
      
      current_statement__ = 3;
      theta = in__.vector(K);
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 3;
        if (jacobian__) {
          current_statement__ = 3;
          assign(theta, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(theta[(sym1__ - 1)], 0, lp__),
            "assigning variable theta");
        } else {
          current_statement__ = 3;
          assign(theta, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(theta[(sym1__ - 1)], 0),
            "assigning variable theta");
        }}
      Eigen::Matrix<local_scalar_t__, -1, 1> w;
      w = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(w, DUMMY_VAR__);
      
      current_statement__ = 4;
      w = in__.vector(K);
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 4;
        if (jacobian__) {
          current_statement__ = 4;
          assign(w, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(w[(sym1__ - 1)], 0, 1, lp__),
            "assigning variable w");
        } else {
          current_statement__ = 4;
          assign(w, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(w[(sym1__ - 1)], 0, 1),
            "assigning variable w");
        }}
      Eigen::Matrix<local_scalar_t__, -1, 1> mu;
      mu = Eigen::Matrix<local_scalar_t__, -1, 1>(num_basis);
      stan::math::fill(mu, DUMMY_VAR__);
      
      current_statement__ = 5;
      mu = in__.vector(num_basis);
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
        current_statement__ = 5;
        if (jacobian__) {
          current_statement__ = 5;
          assign(mu, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(mu[(sym1__ - 1)], 0, lp__),
            "assigning variable mu");
        } else {
          current_statement__ = 5;
          assign(mu, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(mu[(sym1__ - 1)], 0),
            "assigning variable mu");
        }}
      Eigen::Matrix<local_scalar_t__, 1, -1> a_raw;
      a_raw = Eigen::Matrix<local_scalar_t__, 1, -1>(num_basis);
      stan::math::fill(a_raw, DUMMY_VAR__);
      
      current_statement__ = 6;
      a_raw = in__.row_vector(num_basis);
      current_statement__ = 6;
      for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
        current_statement__ = 6;
        if (jacobian__) {
          current_statement__ = 6;
          assign(a_raw, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(a_raw[(sym1__ - 1)], 0, lp__),
            "assigning variable a_raw");
        } else {
          current_statement__ = 6;
          assign(a_raw, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(a_raw[(sym1__ - 1)], 0),
            "assigning variable a_raw");
        }}
      Eigen::Matrix<local_scalar_t__, -1, 1> DP_weights;
      DP_weights = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(DP_weights, DUMMY_VAR__);
      
      current_statement__ = 8;
      assign(DP_weights, cons_list(index_uni(1), nil_index_list()),
        w[(1 - 1)], "assigning variable DP_weights");
      current_statement__ = 11;
      for (int s = 2; s <= (K - 1); ++s) {
        current_statement__ = 9;
        assign(DP_weights, cons_list(index_uni(s), nil_index_list()),
          (w[(s - 1)] *
            prod(
              subtract(1,
                rvalue(w,
                  cons_list(index_min_max(1, (s - 1)), nil_index_list()),
                  "w")))), "assigning variable DP_weights");}
      current_statement__ = 12;
      assign(DP_weights, cons_list(index_uni(K), nil_index_list()),
        (1 -
          sum(
            rvalue(DP_weights,
              cons_list(index_min_max(1, (K - 1)), nil_index_list()),
              "DP_weights"))), "assigning variable DP_weights");
      current_statement__ = 7;
      current_statement__ = 7;
      check_simplex(function__, "DP_weights", DP_weights);
      {
        current_statement__ = 32;
        lp_accum__.add(normal_lpdf<propto__>(beta, 0, 1000));
        current_statement__ = 33;
        lp_accum__.add(exponential_lpdf<propto__>(mu, 1));
        current_statement__ = 34;
        lp_accum__.add(gamma_lpdf<propto__>(nu, 1, 1));
        current_statement__ = 35;
        lp_accum__.add(gamma_lpdf<propto__>(theta, 1, 1));
        current_statement__ = 36;
        lp_accum__.add(beta_lpdf<propto__>(w, 1, alpha));
        current_statement__ = 37;
        lp_accum__.add(normal_lpdf<propto__>(a_raw, 0, mu));
        current_statement__ = 53;
        for (int i = 1; i <= n; ++i) {
          local_scalar_t__ H_Y;
          H_Y = DUMMY_VAR__;
          
          current_statement__ = 38;
          H_Y = 0;
          local_scalar_t__ DH_Y;
          DH_Y = DUMMY_VAR__;
          
          current_statement__ = 39;
          DH_Y = 0;
          current_statement__ = 40;
          validate_non_negative_index("lp_ik", "K", K);
          Eigen::Matrix<local_scalar_t__, -1, 1> lp_ik;
          lp_ik = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
          stan::math::fill(lp_ik, DUMMY_VAR__);
          
          current_statement__ = 42;
          H_Y = multiply(a_raw,
                  to_vector(
                    rvalue(Yspline,
                      cons_list(index_omni(),
                        cons_list(index_uni(location[(i - 1)]),
                          nil_index_list())), "Yspline")));
          current_statement__ = 43;
          DH_Y = multiply(a_raw,
                   to_vector(
                     rvalue(yspline,
                       cons_list(index_omni(),
                         cons_list(index_uni(location[(i - 1)]),
                           nil_index_list())), "yspline")));
          current_statement__ = 50;
          for (int k = 1; k <= K; ++k) {
            current_statement__ = 48;
            if (logical_gt(delta[(i - 1)], 0)) {
              current_statement__ = 46;
              assign(lp_ik, cons_list(index_uni(k), nil_index_list()),
                (((stan::math::log(DP_weights[(k - 1)]) +
                    weibull_lpdf<false>(
                      (H_Y *
                        stan::math::exp(
                          -multiply(
                             rvalue(X,
                               cons_list(index_uni(i),
                                 cons_list(index_min_max(1, p),
                                   nil_index_list())), "X"), beta))),
                      nu[(k - 1)], theta[(k - 1)])) + stan::math::log(DH_Y))
                  -
                  multiply(
                    rvalue(X,
                      cons_list(index_uni(i),
                        cons_list(index_min_max(1, p), nil_index_list())),
                      "X"), beta)), "assigning variable lp_ik");
            } else {
              current_statement__ = 44;
              assign(lp_ik, cons_list(index_uni(k), nil_index_list()),
                (stan::math::log(DP_weights[(k - 1)]) +
                  weibull_lccdf(
                    (H_Y *
                      stan::math::exp(
                        -multiply(
                           rvalue(X,
                             cons_list(index_uni(i),
                               cons_list(index_min_max(1, p),
                                 nil_index_list())), "X"), beta))),
                    nu[(k - 1)], theta[(k - 1)])), "assigning variable lp_ik");
            }}
          current_statement__ = 51;
          lp_accum__.add(log_sum_exp(lp_ik));}
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_trans_unknow_shrinkage_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(p);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      beta = in__.vector(p);
      Eigen::Matrix<double, -1, 1> nu;
      nu = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(nu, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      nu = in__.vector(K);
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 2;
        assign(nu, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(nu[(sym1__ - 1)], 0),
          "assigning variable nu");}
      Eigen::Matrix<double, -1, 1> theta;
      theta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(theta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      theta = in__.vector(K);
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 3;
        assign(theta, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(theta[(sym1__ - 1)], 0),
          "assigning variable theta");}
      Eigen::Matrix<double, -1, 1> w;
      w = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(w, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      w = in__.vector(K);
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 4;
        assign(w, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_constrain(w[(sym1__ - 1)], 0, 1),
          "assigning variable w");}
      Eigen::Matrix<double, -1, 1> mu;
      mu = Eigen::Matrix<double, -1, 1>(num_basis);
      stan::math::fill(mu, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 5;
      mu = in__.vector(num_basis);
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
        current_statement__ = 5;
        assign(mu, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(mu[(sym1__ - 1)], 0),
          "assigning variable mu");}
      Eigen::Matrix<double, 1, -1> a_raw;
      a_raw = Eigen::Matrix<double, 1, -1>(num_basis);
      stan::math::fill(a_raw, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 6;
      a_raw = in__.row_vector(num_basis);
      current_statement__ = 6;
      for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
        current_statement__ = 6;
        assign(a_raw, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(a_raw[(sym1__ - 1)], 0),
          "assigning variable a_raw");}
      Eigen::Matrix<double, -1, 1> DP_weights;
      DP_weights = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(DP_weights, std::numeric_limits<double>::quiet_NaN());
      
      for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(nu[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(theta[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(w[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
        vars__.emplace_back(mu[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
        vars__.emplace_back(a_raw[(sym1__ - 1)]);}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 8;
      assign(DP_weights, cons_list(index_uni(1), nil_index_list()),
        w[(1 - 1)], "assigning variable DP_weights");
      current_statement__ = 11;
      for (int s = 2; s <= (K - 1); ++s) {
        current_statement__ = 9;
        assign(DP_weights, cons_list(index_uni(s), nil_index_list()),
          (w[(s - 1)] *
            prod(
              subtract(1,
                rvalue(w,
                  cons_list(index_min_max(1, (s - 1)), nil_index_list()),
                  "w")))), "assigning variable DP_weights");}
      current_statement__ = 12;
      assign(DP_weights, cons_list(index_uni(K), nil_index_list()),
        (1 -
          sum(
            rvalue(DP_weights,
              cons_list(index_min_max(1, (K - 1)), nil_index_list()),
              "DP_weights"))), "assigning variable DP_weights");
      current_statement__ = 7;
      current_statement__ = 7;
      check_simplex(function__, "DP_weights", DP_weights);
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          vars__.emplace_back(DP_weights[(sym1__ - 1)]);}
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> beta_trans;
      beta_trans = Eigen::Matrix<double, -1, 1>(p);
      stan::math::fill(beta_trans, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> log_lik;
      log_lik = Eigen::Matrix<double, -1, 1>(n);
      stan::math::fill(log_lik, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 15;
      assign(beta_trans, nil_index_list(),
        elt_divide(beta, stan::math::sqrt(sum(elt_multiply(beta, beta)))),
        "assigning variable beta_trans");
      current_statement__ = 31;
      for (int qq = 1; qq <= n; ++qq) {
        double H_Y;
        H_Y = std::numeric_limits<double>::quiet_NaN();
        
        current_statement__ = 16;
        H_Y = 0;
        double DH_Y;
        DH_Y = std::numeric_limits<double>::quiet_NaN();
        
        current_statement__ = 17;
        DH_Y = 0;
        current_statement__ = 18;
        validate_non_negative_index("lp_kk", "K", K);
        Eigen::Matrix<double, -1, 1> lp_kk;
        lp_kk = Eigen::Matrix<double, -1, 1>(K);
        stan::math::fill(lp_kk, std::numeric_limits<double>::quiet_NaN());
        
        current_statement__ = 20;
        H_Y = multiply(a_raw,
                to_vector(
                  rvalue(Yspline,
                    cons_list(index_omni(),
                      cons_list(index_uni(location[(qq - 1)]),
                        nil_index_list())), "Yspline")));
        current_statement__ = 21;
        DH_Y = multiply(a_raw,
                 to_vector(
                   rvalue(yspline,
                     cons_list(index_omni(),
                       cons_list(index_uni(location[(qq - 1)]),
                         nil_index_list())), "yspline")));
        current_statement__ = 28;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 26;
          if (logical_gt(delta[(qq - 1)], 0)) {
            current_statement__ = 24;
            assign(lp_kk, cons_list(index_uni(k), nil_index_list()),
              (((stan::math::log(DP_weights[(k - 1)]) +
                  weibull_lpdf<false>(
                    (H_Y *
                      stan::math::exp(
                        -multiply(
                           rvalue(X,
                             cons_list(index_uni(qq),
                               cons_list(index_min_max(1, p),
                                 nil_index_list())), "X"), beta))),
                    nu[(k - 1)], theta[(k - 1)])) + stan::math::log(DH_Y)) -
                multiply(
                  rvalue(X,
                    cons_list(index_uni(qq),
                      cons_list(index_min_max(1, p), nil_index_list())), "X"),
                  beta)), "assigning variable lp_kk");
          } else {
            current_statement__ = 22;
            assign(lp_kk, cons_list(index_uni(k), nil_index_list()),
              (stan::math::log(DP_weights[(k - 1)]) +
                weibull_lccdf(
                  (H_Y *
                    stan::math::exp(
                      -multiply(
                         rvalue(X,
                           cons_list(index_uni(qq),
                             cons_list(index_min_max(1, p), nil_index_list())),
                           "X"), beta))), nu[(k - 1)], theta[(k - 1)])),
              "assigning variable lp_kk");
          }}
        current_statement__ = 29;
        assign(log_lik, cons_list(index_uni(qq), nil_index_list()),
          log_sum_exp(lp_kk), "assigning variable log_lik");}
      current_statement__ = 13;
      current_statement__ = 13;
      check_unit_vector(function__, "beta_trans", beta_trans);
      for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
        vars__.emplace_back(beta_trans[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        vars__.emplace_back(log_lik[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(p);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 1;
        assign(beta_flat__, nil_index_list(), context__.vals_r("beta"),
          "assigning variable beta_flat__");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          current_statement__ = 1;
          assign(beta, cons_list(index_uni(sym1__), nil_index_list()),
            beta_flat__[(pos__ - 1)], "assigning variable beta");
          current_statement__ = 1;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> nu;
      nu = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(nu, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> nu_flat__;
        current_statement__ = 2;
        assign(nu_flat__, nil_index_list(), context__.vals_r("nu"),
          "assigning variable nu_flat__");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 2;
          assign(nu, cons_list(index_uni(sym1__), nil_index_list()),
            nu_flat__[(pos__ - 1)], "assigning variable nu");
          current_statement__ = 2;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> nu_free__;
      nu_free__ = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(nu_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 2;
        assign(nu_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(nu[(sym1__ - 1)], 0),
          "assigning variable nu_free__");}
      Eigen::Matrix<double, -1, 1> theta;
      theta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(theta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> theta_flat__;
        current_statement__ = 3;
        assign(theta_flat__, nil_index_list(), context__.vals_r("theta"),
          "assigning variable theta_flat__");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 3;
          assign(theta, cons_list(index_uni(sym1__), nil_index_list()),
            theta_flat__[(pos__ - 1)], "assigning variable theta");
          current_statement__ = 3;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> theta_free__;
      theta_free__ = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(theta_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 3;
        assign(theta_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(theta[(sym1__ - 1)], 0),
          "assigning variable theta_free__");}
      Eigen::Matrix<double, -1, 1> w;
      w = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(w, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> w_flat__;
        current_statement__ = 4;
        assign(w_flat__, nil_index_list(), context__.vals_r("w"),
          "assigning variable w_flat__");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 4;
          assign(w, cons_list(index_uni(sym1__), nil_index_list()),
            w_flat__[(pos__ - 1)], "assigning variable w");
          current_statement__ = 4;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> w_free__;
      w_free__ = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(w_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 4;
        assign(w_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_free(w[(sym1__ - 1)], 0, 1),
          "assigning variable w_free__");}
      Eigen::Matrix<double, -1, 1> mu;
      mu = Eigen::Matrix<double, -1, 1>(num_basis);
      stan::math::fill(mu, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> mu_flat__;
        current_statement__ = 5;
        assign(mu_flat__, nil_index_list(), context__.vals_r("mu"),
          "assigning variable mu_flat__");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
          current_statement__ = 5;
          assign(mu, cons_list(index_uni(sym1__), nil_index_list()),
            mu_flat__[(pos__ - 1)], "assigning variable mu");
          current_statement__ = 5;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> mu_free__;
      mu_free__ = Eigen::Matrix<double, -1, 1>(num_basis);
      stan::math::fill(mu_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
        current_statement__ = 5;
        assign(mu_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(mu[(sym1__ - 1)], 0),
          "assigning variable mu_free__");}
      Eigen::Matrix<double, 1, -1> a_raw;
      a_raw = Eigen::Matrix<double, 1, -1>(num_basis);
      stan::math::fill(a_raw, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> a_raw_flat__;
        current_statement__ = 6;
        assign(a_raw_flat__, nil_index_list(), context__.vals_r("a_raw"),
          "assigning variable a_raw_flat__");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
          current_statement__ = 6;
          assign(a_raw, cons_list(index_uni(sym1__), nil_index_list()),
            a_raw_flat__[(pos__ - 1)], "assigning variable a_raw");
          current_statement__ = 6;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, 1, -1> a_raw_free__;
      a_raw_free__ = Eigen::Matrix<double, 1, -1>(num_basis);
      stan::math::fill(a_raw_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 6;
      for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
        current_statement__ = 6;
        assign(a_raw_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(a_raw[(sym1__ - 1)], 0),
          "assigning variable a_raw_free__");}
      for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(nu_free__[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(theta_free__[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(w_free__[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
        vars__.emplace_back(mu_free__[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
        vars__.emplace_back(a_raw_free__[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("beta");
    names__.emplace_back("nu");
    names__.emplace_back("theta");
    names__.emplace_back("w");
    names__.emplace_back("mu");
    names__.emplace_back("a_raw");
    names__.emplace_back("DP_weights");
    names__.emplace_back("beta_trans");
    names__.emplace_back("log_lik");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(p)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(num_basis)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(num_basis)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(p)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "nu" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "w" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "a_raw" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "DP_weights" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "beta_trans" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "nu" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "w" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= num_basis; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "a_raw" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "DP_weights" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "beta_trans" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << p << "},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" << num_basis << "},\"block\":\"parameters\"},{\"name\":\"a_raw\",\"type\":{\"name\":\"vector\",\"length\":" << num_basis << "},\"block\":\"parameters\"},{\"name\":\"DP_weights\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_trans\",\"type\":{\"name\":\"vector\",\"length\":" << p << "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" << n << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << p << "},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" << num_basis << "},\"block\":\"parameters\"},{\"name\":\"a_raw\",\"type\":{\"name\":\"vector\",\"length\":" << num_basis << "},\"block\":\"parameters\"},{\"name\":\"DP_weights\",\"type\":{\"name\":\"vector\",\"length\":" << (K - 1) << "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_trans\",\"type\":{\"name\":\"vector\",\"length\":" << p << "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" << n << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_trans_unknow_shrinkage_namespace::model_trans_unknow_shrinkage;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_trans_unknow_shrinkage_namespace::profiles__;
}
#endif
#endif
